@hostname = http://localhost:3000

### Get all songs
get {{hostname}}/songs

### get a song
get {{hostname}}/songs/1

### create a new song
post {{hostname}}/songs
Content-Type: application/json

{
    "title": "Lose",
    "artists": ["Otami"],
    "releaseDate": "2022-12-08",
    "duration": "03:16"
}

### update a song
PUT {{hostname}}/songs/1

### delete a song
delete {{hostname}}/songs/1