@hostname = http://localhost:3000

### Get all songs
get {{hostname}}/songs

### get a song
get {{hostname}}/songs/1

### create a new song
post {{hostname}}/songs
Content-Type: application/json

{
    "me": "ew"
}

### update a song
PUT {{hostname}}/songs/1

### delete a song
delete {{hostname}}/songs/1